### ISSUE TITLE
[Bug] Permission to generate image on oaidalleapiprodscus.blob.core.windows.net lost

### ISSUE THREAD

**Issue by limex** [microtower00/obsidian-ai-images#9]
Hi,

I was able to successfully create an image that was added to the .md file.
But after some hours the permissions where lost 

File: 
https://oaidalleapiprodscus.blob.core.windows.net/private/org-1PlG9DkqsuCgTYoVf2FNvHSH/user-KiuxlI0Ec0HMPJDVsOXiUPl0/img-lIQCqReloziEWXkaTdgKSWJQ.png?st=2022-12-07T05%3A57%3A36Z&se=2022-12-07T07%3A57%3A36Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2022-12-07T06%3A57%3A36Z&ske=2022-12-08T06%3A57%3A36Z&sks=b&skv=2021-08-06&sig=dYTaV5LyMCP8657fYbagM3%2B%2BkJ0PHzSqx%2BZkH6i2SPw%3D

if opened in browser:

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:087df563-701e-009a-3a18-0acae7000000 Time:2022-12-07T08:46:07.9437969Z</Message>
</Error>

Is this an issue on the openai side?
Shouldn't the images be copied to the lokal markdown folder?

**Comment by microtower00** [comment]
I thought this might happen, and saving the image is on the list of features to add. The idea is to download the image, save it to the default attachment folder specified in the settings, and then link it in the file

**Comment by microtower00** [comment]
I'm having problems trying to get the image from the generation url. It seems like OpenAI is blocking my request over some CORS issues, and I really don't know if there is something that I can do about it.
![image](https://user-images.githubusercontent.com/58070348/206200704-c6f1ccef-a640-4101-a3f3-513b396deb04.png)
Using this code, I get this response.
![image](https://user-images.githubusercontent.com/58070348/206200940-e2dbfedf-02ef-448e-95ea-6b9dd64c8f73.png)

Setting the request to ```no-cors``` only suppresses the error and is not useful unfortunately.

This might be pretty bad, because if this turns out to be a serious issue, the plugin is pretty much useless.
I'm going to try and find another solution as time allows me.

**Comment by microtower00** [comment]
What I don't get is why I'm able to access the resource through a web browser but not download it.
